[build]
buildCommand = "mvn package -DskipTests"

[variables]
SPRING_DATASOURCE_URL = "jdbc:postgresql://${{Postgres.PGHOST}}:${{Postgres.PGPORT}}/${{Postgres.PGDATABASE}}"
SPRING_DATASOURCE_USERNAME = "${{Postgres.PGUSER}}"
SPRING_DATASOURCE_PASSWORD = "${{Postgres.PGPASSWORD}}"
