spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:5432/feedbackdb}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
